version: "3.8"
services:
  nginx:
    container_name: nginx_medbot_prod
    image: medbot/nginx:$TAG
    restart: on-failure
    volumes:
      - type: bind
        source: ./volume/nginx
        target: /etc/nginx/templates
        read_only: true
      - type: bind
        source: ./ssl
        target: /etc/nginx/ssl
        read_only: true
      - type: bind
        source: ./logs/nginx
        target: /usr/app/logs
        read_only: false
    expose:
      - 80
      - 443
    ports:
      - 80:80
      - 443:443
    networks:
      - medbot_bridge_prod
    depends_on:
      - fastify
      - adminer

  fastify:
    container_name: fastify_prod
    image: medbot/fastify:$TAG
    healthcheck:
      test: ["CMD", "wget http://localhost:8000/api/healthcheck || exit 1"]
      interval: 20s
      timeout: 20s
      retries: 3
      start_period: 2m
    volumes:
      - type: bind
        source: ./logs/fastify
        target: /usr/app/logs
        read_only: false
    ports:
      - '8000:8000'
    expose:
      - 8000
    env_file:
      - ".env.prod"
    networks:
      - medbot_bridge_prod
    depends_on:
      - db

  adminer:
    container_name: adminer_prod
    image: adminer
    ports:
      - 8080:8080
    networks:
      - medbot_bridge_prod
    depends_on:
      - db

  db:
    container_name: mysql_db_prod
    platform: linux/amd64
    image: mysql:8.2.0
    ports:
      - "3306:3306"
    expose:
      - 3306
    volumes:
      - "./volume/db:/var/lib/mysql"
    env_file:
      - ".env.prod"
    networks:
      - medbot_bridge_prod

networks:
  medbot_bridge_prod:
