version: "3.8"
services:
  fastify:
    container_name: fastify_prod
    image: medbot/fastify:$TAG
    healthcheck:
      test: ["CMD", "curl -sS http://127.0.0.1:8000/api/healthcheck || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 6
      start_period: 10s
    volumes:
      - type: bind
        source: ./logs/fastify
        target: /usr/app/logs/fastify
        read_only: false
    ports:
      - '8000:8000'
    expose:
      - 8000
    env_file:
      - ".env.prod"
    networks:
      - medbot_bridge_prod
    depends_on:
      - db

  adminer:
    container_name: adminer_prod
    image: adminer
    ports:
      - 8081:8080
    networks:
      - medbot_bridge_prod
    depends_on:
      - db

  db:
    container_name: mysql_db_prod
    platform: linux/amd64
    image: mysql:8.2.0
    ports:
      - "3307:3306"
    expose:
      - 3307
    volumes:
      - "./volume/db:/var/lib/mysql"
    env_file:
      - ".env.prod"
    networks:
      - medbot_bridge_prod

networks:
  medbot_bridge_prod:
