version: "3.8"
services:
  fastify:
    container_name: fastify_stage
    image: medbot/fastify:$TAG
    healthcheck:
      test: ["CMD", "curl -sS http://127.0.0.1:3000/api/healthcheck || exit 1"]
      interval: 20s
      timeout: 20s
      retries: 3
      start_period: 2m
    volumes:
      - type: bind
        source: ./logs/fastify
        target: /usr/app/logs/fastify
        read_only: false
    ports:
      - '3000:3000'
    expose:
      - 3000
    env_file:
      - ".env.stage"
    networks:
      - medbot_bridge_stage
    depends_on:
      - db

  adminer:
    container_name: adminer_stage
    image: adminer
    ports:
      - 8080:8080
    networks:
      - medbot_bridge_stage
    depends_on:
      - db

  db:
    container_name: mysql_db_stage
    platform: linux/amd64
    image: mysql:8.2.0
    ports:
      - "3306:3306"
    expose:
      - 3306
    volumes:
      - "./volume/db:/var/lib/mysql"
    env_file:
      - ".env.stage"
    networks:
      - medbot_bridge_stage

networks:
  medbot_bridge_stage:

