version: "3.8"
services:
  fastify_stage:
    container_name: fastify_stage
    image: medbot/fastify:$TAG
    healthcheck:
      test: ["CMD", "curl", "-sS", "http://127.0.0.1:3000/api/healthcheck"]
      interval: 5s
      timeout: 5s
      retries: 6
      start_period: 10s
    volumes:
      - type: bind
        source: ./stage/logs/fastify
        target: /usr/app/logs/fastify
        read_only: false
    ports:
      - '3000:3000'
    expose:
      - 3000
    env_file:
      - "./stage/.env"
    networks:
      - medbot_bridge_stage
    depends_on:
      - db_stage

  fastify_prod:
    container_name: fastify_prod
    image: medbot/fastify:$TAG
    healthcheck:
      test: ["CMD", "curl", "-sS", "http://127.0.0.1:8000/api/healthcheck"]
      interval: 5s
      timeout: 5s
      retries: 6
      start_period: 10s
    volumes:
      - type: bind
        source: ./prod/logs/fastify
        target: /usr/app/logs/fastify
        read_only: false
    ports:
      - '8000:8000'
    expose:
      - 8000
    env_file:
      - "./prod/.env"
    networks:
      - medbot_bridge_prod
    depends_on:
      - db_prod

  adminer_stage:
    container_name: adminer_stage
    image: adminer
    ports:
      - 8080:8080
    networks:
      - medbot_bridge_stage
    depends_on:
      - db_stage

  adminer_prod:
    container_name: adminer_prod
    image: adminer
    ports:
      - 8081:8080
    networks:
      - medbot_bridge_prod
    depends_on:
      - db_prod

  db_stage:
    container_name: mysql_db_stage
    platform: linux/amd64
    image: mysql:8.2.0
    volumes:
      - "./stage/volume/db:/var/lib/mysql"
    env_file:
      - "./stage/.env"
    networks:
      - medbot_bridge_stage

  db_prod:
    container_name: mysql_db_prod
    platform: linux/amd64
    image: mysql:8.2.0
    volumes:
      - "./prod/volume/db:/var/lib/mysql"
    env_file:
      - "./prod/.env"
    networks:
      - medbot_bridge_prod

networks:
  medbot_bridge_prod:
    name: medbot_bridge_prod
    external: true
  medbot_bridge_stage:
    name: medbot_bridge_stage
    external: true
