export enum ROUTES {
  ROOT = '/',
  LOGIN = '/login',
  REGISTER = '/register',
  DASHBOARD = '/dashboard',
  PRODUCTS = '/dashboard/products',
  CREATE_PRODUCT = '/dashboard/product/create',
  EDIT_PRODUCT = '/dashboard/product/:id',
  USERS = '/dashboard/users',
  USER = '/dashboard/user/:userId',
  USER_ORDERS = '/dashboard/user/:userId/orders',
  USER_APPOINTMENTS = '/dashboard/user/:userId/appointments',
  ORDERS = '/dashboard/orders',
  APPOINTMENTS = '/dashboard/appointments',
  I18N = '/dashboard/i18n',
  I18N_NAMESPACE = '/dashboard/i18n/:lang/:namespace',
  I18N_CREATE = '/dashboard/i18n/:lang/:namespace/create',
  I18N_UPDATE = '/dashboard/i18n/:lang/:namespace/:id',
}
