name: Deploy

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

env:
  NODE_VERSION: 21.7.2
  NODE_ENV: production
  FASTIFY_IMAGE: medbot/fastify:${{github.sha}}
  ENV: ${{ github.event_name == 'workflow_dispatch' && 'prod' || 'stage' }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install deps and build admin
        working-directory: ./admin
        run: |
          npm ci --include=dev
          npm run build

      - name: Install deps and build server
        working-directory: ./server
        run: |
          npm ci --include=dev
          npm run build

      - name: Install deps and build webapp
        working-directory: ./webapp
        run: |
          npm ci --include=dev
          npm run build

      - name: Build docker image
        run: |
          docker build -t ${{env.FASTIFY_IMAGE}} ./server

      - name: Save docker image
        run: |
          mkdir images
          docker save -o ./fastify.tar ${{env.FASTIFY_IMAGE}}
          chmod a+r ./fastify.tar

      - name: Copy images dir
        uses: appleboy/scp-action@v0.1.6
        with:
          host: ${{ secrets.HOSTNAME }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: "fastify.tar"
          target: ${{ secrets.IMAGES_DIR }}

      - name: Copy deploy dir
        uses: appleboy/scp-action@v0.1.6
        with:
          host: ${{ secrets.HOSTNAME }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: ".deploy/*"
          target: ${{ secrets.DIR }}
          strip_components: 1

      - name: Copy admin dir
        uses: appleboy/scp-action@v0.1.6
        with:
          host: ${{ secrets.HOSTNAME }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: "admin/build/*"
          target: ${{ secrets.DIR }}/${{ env.ENV }}/static/admin/
          strip_components: 2

      - name: Copy webapp dir
        uses: appleboy/scp-action@v0.1.6
        with:
          host: ${{ secrets.HOSTNAME }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: "webapp/build/*"
          target: ${{ secrets.DIR }}/${{ env.ENV }}/static/webapp/
          strip_components: 2

      - name: Start containers
        uses: appleboy/ssh-action@v1.0.1
        env:
          TAG: ${{ github.sha }}
          DIR: ${{ secrets.DIR }}
          IMAGES_DIR: ${{ secrets.IMAGES_DIR }}
          ENV: ${{ env.ENV }}
        with:
          host: ${{ secrets.HOSTNAME }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          envs: TAG,DIR,ENV,IMAGES_DIR
          script_stop: true
          script: |
            bash ${{ secrets.DIR }}/scripts/run-containers.sh
            bash ${{ secrets.DIR }}/scripts/migrate.sh

      - name: Setup cron jobs
        uses: appleboy/ssh-action@v1.0.1
        if: github.ref == 'refs/heads/main'
        env:
          DIR: ${{ secrets.DIR }}
        with:
          host: ${{ secrets.HOSTNAME }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          envs: DIR
          script_stop: true
          script: |
            bash ${{ secrets.DIR }}/scripts/setup-crontab.sh
